<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RuleBasedValidation.Engine\RuleBasedValidation.Engine.csproj" />
    <ProjectReference Include="..\..\RuleBasedValidation.Rules\RuleBasedValidation.Rules.csproj" />
    <ProjectReference Include="..\ValidationEngine.Core\ValidationEngine.Core.csproj" />
  </ItemGroup>

</Project>
